### ISSUE TITLE
路径参数该如何配置?

### ISSUE THREAD

**Issue by sumn20** [maihaoche/MybatisGeneratorPlugin#1]
请问路径参数这里该如何配置 我配置了包名但是并没用

**Comment by kauchy** [comment]
LGTM

**Comment by WangYangYang2014** [comment]
下图是设置路径的示例：
[路径配置示例](http://of8cu1h2w.bkt.clouddn.com/%E8%B7%AF%E5%BE%84%E5%8F%82%E6%95%B0%E8%AE%BE%E7%BD%AE%E7%A4%BA%E4%BE%8B.png)
其中模块名和包路径都必须是项目中真实对应的模块和路径。如果输入的包名和模块名不是项目中已有的，那么生成的代码会在项目文件目录中，不会引入项目编译。
