### ISSUE TITLE
有个疑问想问下，又没有 mail address，索性就直接 new issue 了

### ISSUE THREAD

**Issue by Nickolas-Evans** [maihaoche/MybatisGeneratorPlugin#2]
技术选型的时候，为啥没有选用 mybatis generator 而是选择自己重复造轮？

http://www.mybatis.org/generator/

**Comment by WangYangYang2014** [comment]
我刚发现这个。技术选型的时候，有人直接把http://www.mybatis.org/generator/的代码直接拉过来了。
这个插件我会赶紧从插件仓库移除。
